kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Values.global.compositionName }}-composition-panel-button-delete
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  widgetData:
    icon: fa-trash
    type: default
    shape: circle
    clickActionId: delete
    actions:
      rest:
        - id: delete
          resourceRefId: delete
          type: rest
          onSuccessNavigateTo: /compositions
  resourcesRefs:
    items:
      - id: delete
        apiVersion: {{ .Values.global.compositionGroup }}/{{ .Values.global.compositionInstalledVersion }}
        resource: {{ .Values.global.compositionResource }}
        name: {{ .Values.global.compositionName }}
        namespace: {{ .Values.global.compositionNamespace }}
        verb: DELETE