kind: FlowChart
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Values.global.compositionName }}-composition-status-panel-flowchart
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  widgetData:
    data: []
  widgetDataTemplate:
    - forPath: data
      expression: ${ .nodes }
  apiRef:
    name: {{ .Values.global.compositionName }}-composition-status
    namespace: {{ .Values.global.compositionNamespace }}