kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Release.Name }}-composition-finops-column-panel-2
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    title: Usage and Optimization
    items:
      - resourceRefId: row-1
      - resourceRefId: row-2
  resourcesRefs:
    - id:  row-1
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: {{ .Release.Name }}-composition-finops-column-panel-2-row-1
      namespace: {{ .Release.Namespace }}
      resource: rows
      verb: GET
    - id:  row-2
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: {{ .Release.Name }}-composition-finops-column-panel-2-row-2-paragraph
      namespace: {{ .Release.Namespace }}
      resource: paragraphs
      verb: GET
