apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: {{ .Release.Name }}-composition-finops-panel-row-3-linechart
spec:
  api:
  - name: getComposition
    path: "/apis/{{ .Values.global.compositionApiVersion }}/namespaces/{{ .Release.Namespace }}/{{ .Values.global.compositionResource }}/{{ .Release.Name }}"
    verb: GET
    headers:
    - 'Accept: application/json'
  - name: metrics
    dependsOn: 
      name: getComposition
    endpointRef: 
      name: finops-database-handler-endpoint
      namespace: krateo-system
    path: "/compute/metrics"
    verb: POST
    payload: |
      ${ {table_name: "{{ .Values.global.tableName }}_res", resource_name: .getComposition.spec.name, resource_group_name: .getComposition.spec.resourceGroupName } }
    headers:
    - 'Accept: application/json'
    - 'Content-Type: application/json'
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: {{ .Release.Name }}-composition-finops-panel-row-3-table
spec:
  api:
  - name: getComposition
    path: "/apis/{{ .Values.global.compositionApiVersion }}/namespaces/{{ .Release.Namespace }}/{{ .Values.global.compositionResource }}/{{ .Release.Name }}"
    verb: GET
    headers:
    - 'Accept: application/json'
    filter: |
      [ .spec.optimization | fromjson | .[] | { resourceid: (.resourceid | split("/") | .[-1]), metricname: .metricname, unit: .unit, optimizeFrom: .optimization.from, resourceDelta: .optimization.resourceDelta, optimizeTo: .optimization.to  }]