apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: {{ .Values.global.compositionName }}-composition-values
  namespace: {{ .Values.global.compositionNamespace }}
spec:
  api:
  - name: getCompositionCompleted
    path: "/call?apiVersion=templates.krateo.io%2Fv1&resource=restactions&name={{ .Values.global.compositionName }}-composition-status&namespace={{ .Values.global.compositionNamespace }}"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace: {{ .Values.global.krateoNamespace }}
    headers:
    - 'Accept: application/json'
    continueOnError: true
    errorKey: getCompositionCompletedError
    exportJwt: true
  - name: getValues
    path: "/apis/{{ .Values.global.compositionGroup }}/{{ .Values.global.compositionInstalledVersion }}/namespaces/{{ .Values.global.compositionNamespace }}/{{ .Values.global.compositionResource }}/{{ .Values.global.compositionName }}"
    verb: GET
  filter: >
    {
      compositionCompleted: .getCompositionCompleted.status.compositionCompleted,
      values: (.getValues | del(.metadata.managedFields) // [])
    }