kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Values.global.compositionName }}-composition-finops-column-panel-1-row-2
spec:
  widgetData:
    items:
      - resourceRefId: cost-piechart-paragraph
        size: 12
      - resourceRefId: cost-linechart-paragraph
        size: 12
  resourcesRefs:
    items:
    - id:  cost-piechart-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: {{ .Values.global.compositionName }}-composition-finops-column-panel-1-row-2-piechart-paragraph
      namespace: {{ .Values.global.compositionNamespace }}
      resource: paragraphs
      verb: GET
    - id: cost-linechart-paragraph
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: {{ .Values.global.compositionName }}-composition-finops-column-panel-1-row-2-linechart-paragraph
      namespace: {{ .Values.global.compositionNamespace }}
      resource: paragraphs
      verb: GET