kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Release.Name }}-composition-finops-column-panel-1-row-1
  namespace: {{ .Release.Namespace }}
spec: 
  widgetData:
    items:
      - resourceRefId: cost-piechart
        size: 6
      - resourceRefId: cost-linechart
        size: 18
  resourcesRefs:
    - id:  cost-piechart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: {{ .Release.Name }}-composition-finops-column-panel-1-row-1-piechart
      namespace: {{ .Release.Namespace }}
      resource: piecharts
      verb: GET
    - id: cost-linechart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: {{ .Release.Name }}-composition-finops-column-panel-1-row-1-linechart
      namespace: {{ .Release.Namespace }}
      resource: linecharts
      verb: GET
