kind: Row
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Values.global.compositionName }}-composition-finops-column-panel-1-row-1
  namespace: {{ .Values.global.compositionNamespace }}
spec: 
  widgetData:
    items:
      - resourceRefId: cost-piechart
        size: 6
      - resourceRefId: cost-linechart
        size: 18
  resourcesRefs:
    items:
    - id:  cost-piechart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: {{ .Values.global.compositionName }}-composition-finops-column-panel-1-row-1-piechart
      namespace: {{ .Values.global.compositionNamespace }}
      resource: piecharts
      verb: GET
    - id: cost-linechart
      apiVersion: widgets.templates.krateo.io/v1beta1
      name: {{ .Values.global.compositionName }}-composition-finops-column-panel-1-row-1-linechart
      namespace: {{ .Values.global.compositionNamespace }}
      resource: linecharts
      verb: GET
