kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Release.Name }}-composition-finops-column-panel-1-row-2-piechart-paragraph
spec:
  widgetData:
    text: "The overall costs for this composition, grouped by type of resource."
---
kind: Paragraph
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: {{ .Release.Name }}-composition-finops-column-panel-1-row-2-linechart-paragraph
spec:
  widgetData:
    text: "The breakdown of the costs of the composition with cumulative lines."